### PR TITLE
Added Mars Club members

### PR DESCRIPTION
**Pull request by debjitpal5040**
Linked Issue: #5 
Kindly review this please

## Changes
- Added pie chart for visualisation of success rate of Mars club members
link of the notebook : https://colab.research.google.com/drive/1AfEJFtO94H5y8iu79LgViE1BCdHgPsKl?usp=sharing

### CODE REVIEW

**Comment by Codehackerone** [comment]
The pie chart is on point. But the colours are looking a bit weird, so please change those. And if you can, try to include the percentage also.

**Comment by debjitpal5040** [comment]
Okay sure... I will change the colours and include the percentage.

**Comment by debjitpal5040** [comment]
@Codehackerone okay now check please.

**Comment by Codehackerone** [comment]
```
def make_autopct(values):
    def my_autopct(pct):
        total = sum(values)
        val = int(round(pct*total/100.0))
        return '{p:.2f}%  ({v:d})'.format(p=pct,v=val)
    return my_autopct
```
Why did you make 2 functions?

**Comment by Codehackerone** [comment]
One more small change required:-
- Set the dpi to 150

**Comment by debjitpal5040** [comment]
> ```
> def make_autopct(values):
>    def my_autopct(pct):
>        total = sum(values)
>        val = int(round(pct*total/100.0))
>        return '{p:.2f}%  ({v:d})'.format(p=pct,v=val)
>    return my_autopct
> ```
> 
> 
>      
>   
> 
> Why did you make 2 functions?

Nothing particular, just for more visible clarity. 😅 If you say I will merge this to one function 😅

**Comment by debjitpal5040** [comment]
> One more small change required:-
> 
> * Set the dpi to 150

Sure, I will set it😃

**Comment by Codehackerone** [comment]
> > ```
> > def make_autopct(values):
> >    def my_autopct(pct):
> >        total = sum(values)
> >        val = int(round(pct*total/100.0))
> >        return '{p:.2f}%  ({v:d})'.format(p=pct,v=val)
> >    return my_autopct
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Why did you make 2 functions?
> 
> Nothing particular, just for more visible clarity. 😅 If you say I will merge this to one function 😅

Please make it a single function and the function should have been defined in a separate cell.

**Comment by debjitpal5040** [comment]
> > > ```
> > > def make_autopct(values):
> > >    def my_autopct(pct):
> > >        total = sum(values)
> > >        val = int(round(pct*total/100.0))
> > >        return '{p:.2f}%  ({v:d})'.format(p=pct,v=val)
> > >    return my_autopct
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Why did you make 2 functions?
> > 
> > 
> > Nothing particular, just for more visible clarity. 😅 If you say I will merge this to one function 😅
> 
> 
> Please make it a single function and the function should have been defined in a separate cell.

Okay I have set the dpi as you told and managed to use the autopct using lambda function, I think you will like it. @Codehackerone now check once please.

**Review by Codehackerone — APPROVED** [review]
Nicely done. Loved it.

**Pull request merged**
